version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
  # We want updates for our pinned base image.
  - package-ecosystem: docker
    directory: '/'
    schedule:
      interval: weekly
  # We don't want major upgrades for npm packages.
  - package-ecosystem: npm
    directory: '/'
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
